stages:
  - publish
  - deploy

variables:
  TAG_LATEST: $CI_REGISTRY_IMAGE:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  TAG_BRANCH: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

publish:
  image: docker:latest
  stage: publish
  services:
    - docker:dind
  variables:
    DOCKER_BUILDKIT: 1
    DOCKER_TLS_CERTDIR: "/certs"
  only:
    - main
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker pull $TAG_BRANCH || true
  script:
    - docker build --build-arg PYPI_ADDRESS="https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/api/v4/projects/41730160/packages/pypi/simple" -t $TAG_BRANCH -t $TAG_COMMIT -t $TAG_LATEST .
    - docker push $TAG_BRANCH
    - docker push $TAG_COMMIT
    - docker push $TAG_LATEST
